name: "CI"

on:
  pull_request:
  push:
    branches:
      - "master"
      - "renovate/*"

env:
  INI_VALUES: zend.assertions=1,error_reporting=-1

jobs:
  composer-json-lint:
    name: "Lint composer.json"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.3"

    steps:
      - uses: "actions/checkout@v5"
      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
          tools: composer-normalize,composer-require-checker
      - uses: "ramsey/composer-install@v3"

      - run: "composer validate --strict"
      - run: "composer-normalize --dry-run"
      - run: "composer-require-checker"

  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.4"
        code-coverage:
          - "none"
        include:
          - php-version: "8.3"
            code-coverage: "pcov"

    steps:
      - uses: "actions/checkout@v5"
      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "${{ matrix.code-coverage }}"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
      - uses: "ramsey/composer-install@v3"
        with:
          composer-options: "--ignore-platform-req=php"

      - run: "vendor/bin/phpunit --no-coverage --no-logging"
        if: ${{ matrix.code-coverage == 'none' }}
        timeout-minutes: 3

      - run: "vendor/bin/phpunit"
        if: ${{ matrix.code-coverage != 'none' }}
        timeout-minutes: 3

      - name: "Infection"
        if: ${{ matrix.code-coverage != 'none' }}
        timeout-minutes: 10
        run: "vendor/bin/infection --threads=$(nproc) --skip-initial-tests --coverage=coverage --show-mutations --verbose --min-msi=100 --logger-github"
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.3"

    steps:
      - uses: "actions/checkout@v5"
      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
      - uses: "ramsey/composer-install@v3"

      - run: "vendor/bin/php-cs-fixer fix --verbose --dry-run --diff"

  static-analysis:
    name: "Static Analysis"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.3"

    steps:
      - uses: "actions/checkout@v5"
      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
      - uses: "ramsey/composer-install@v3"

      - run: "vendor/bin/phpstan analyse --no-progress --error-format=github"
